--
-- PostgreSQL database dump
--

\restrict dJhcsdAKxg4FO7PebPGmCwbVFGxAFD968GZ6kDQMTBTfN8lymz3VUZjQf5ZGU9C

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-06 13:59:01 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17292)
-- Name: items_cocina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.items_cocina (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    completado boolean,
    nombre character varying(255) NOT NULL,
    notas character varying(255),
    producto_id integer NOT NULL,
    pedido_id bigint NOT NULL
);


ALTER TABLE public.items_cocina OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17302)
-- Name: items_cocina_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.items_cocina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_cocina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17303)
-- Name: pedidos_cocina; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedidos_cocina (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    estado character varying(255),
    hora character varying(255),
    mesa_numero integer NOT NULL,
    orden_id character varying(255) NOT NULL
);


ALTER TABLE public.pedidos_cocina OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17311)
-- Name: pedidos_cocina_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedidos_cocina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_cocina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4473 (class 0 OID 17292)
-- Dependencies: 219
-- Data for Name: items_cocina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.items_cocina (id, cantidad, completado, nombre, notas, producto_id, pedido_id) FROM stdin;
59	2	t	foca		26	42
60	2	t	foca		26	43
61	2	t	gato		27	44
62	2	t	gato		27	45
63	1	t	foca		26	46
64	1	t	foca		26	47
65	2	t	gato		27	48
66	2	t	foca		26	49
67	2	t	gato		27	50
70	2	t	gato		27	53
69	2	t	gato		27	52
68	2	t	gato		27	51
\.


--
-- TOC entry 4475 (class 0 OID 17303)
-- Dependencies: 221
-- Data for Name: pedidos_cocina; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedidos_cocina (id, created_at, estado, hora, mesa_numero, orden_id) FROM stdin;
42	2026-05-21 19:03:06.206177	LISTO	19:03	1	ORD-1779408186186
43	2026-05-21 19:14:42.247064	LISTO	19:14	2	ORD-1779408882229
44	2026-05-21 19:15:18.069085	LISTO	19:15	1	ORD-1779408918050
45	2026-05-21 19:20:32.173994	LISTO	19:20	3	ORD-1779409232157
46	2026-05-21 19:20:53.210735	LISTO	19:20	2	ORD-1779409253192
47	2026-05-21 19:21:05.499215	LISTO	19:21	3	ORD-1779409265480
48	2026-05-21 19:36:15.131033	LISTO	19:36	1	ORD-1779410174819
49	2026-05-22 01:52:52.358927	LISTO	01:52	1	ORD-1779432771893
50	2026-05-22 01:55:37.495504	LISTO	01:55	1	ORD-1779432937472
53	2026-05-22 02:24:20.758558	LISTO	02:24	1	ORD-1779434660736
52	2026-05-22 02:15:34.713793	LISTO	02:15	4	ORD-1779434134692
51	2026-05-22 02:15:23.892951	LISTO	02:15	6	ORD-1779434123870
\.


--
-- TOC entry 4482 (class 0 OID 0)
-- Dependencies: 220
-- Name: items_cocina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.items_cocina_id_seq', 130, true);


--
-- TOC entry 4483 (class 0 OID 0)
-- Dependencies: 222
-- Name: pedidos_cocina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedidos_cocina_id_seq', 97, true);


--
-- TOC entry 4320 (class 2606 OID 17313)
-- Name: items_cocina items_cocina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items_cocina
    ADD CONSTRAINT items_cocina_pkey PRIMARY KEY (id);


--
-- TOC entry 4322 (class 2606 OID 17315)
-- Name: pedidos_cocina pedidos_cocina_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos_cocina
    ADD CONSTRAINT pedidos_cocina_pkey PRIMARY KEY (id);


--
-- TOC entry 4324 (class 2606 OID 17317)
-- Name: pedidos_cocina ukp2qj21k98x59c2w1truyusatb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidos_cocina
    ADD CONSTRAINT ukp2qj21k98x59c2w1truyusatb UNIQUE (orden_id);


--
-- TOC entry 4325 (class 2606 OID 17318)
-- Name: items_cocina fk674984xmemy72key90hsvp0v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items_cocina
    ADD CONSTRAINT fk674984xmemy72key90hsvp0v FOREIGN KEY (pedido_id) REFERENCES public.pedidos_cocina(id);


-- Completed on 2026-06-06 13:59:01 -05

--
-- PostgreSQL database dump complete
--

\unrestrict dJhcsdAKxg4FO7PebPGmCwbVFGxAFD968GZ6kDQMTBTfN8lymz3VUZjQf5ZGU9C

