--
-- PostgreSQL database dump
--

\restrict L6YmxKmnHpaSZm6hdYKSAcgtfDdga4aQc7hakV8ZbQ78hIaabsRZzU6YB2imX91

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-06 14:02:23 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17423)
-- Name: reservas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservas (
    id bigint NOT NULL,
    alergias character varying(500),
    apellido character varying(255),
    codigo character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    estado character varying(255) NOT NULL,
    experiencia character varying(255) NOT NULL,
    fecha date NOT NULL,
    hora character varying(255) NOT NULL,
    necesidades character varying(500),
    nombre character varying(255) NOT NULL,
    personas integer NOT NULL,
    requerimientos character varying(500),
    telefono character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT reservas_estado_check CHECK (((estado)::text = ANY (ARRAY[('PENDIENTE'::character varying)::text, ('ACEPTADA'::character varying)::text, ('CANCELADA'::character varying)::text, ('COMPLETADA'::character varying)::text])))
);


ALTER TABLE public.reservas OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17438)
-- Name: reservas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4466 (class 0 OID 17423)
-- Dependencies: 219
-- Data for Name: reservas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservas (id, alergias, apellido, codigo, created_at, email, estado, experiencia, fecha, hora, necesidades, nombre, personas, requerimientos, telefono, updated_at) FROM stdin;
1	\N	\N	RES-62BC156B	2026-05-22 12:18:15.411004	juan@test.com	PENDIENTE	A la carta	2025-12-25	20:00	\N	Juan	4	\N	\N	2026-05-22 12:18:15.411004
2	Gripe	Perez	RES-CC5F9C24	2026-05-22 12:51:08.302303	stiven@gmail.com	PENDIENTE	A la carta	2026-05-29	07:00	Cjo	stiven	4	Nada	995214654	2026-05-22 12:51:08.303309
3	mani	Ordoñez	RES-CDDB346C	2026-05-22 12:52:06.408078	stefi@gmail.com	COMPLETADA	A la carta	2026-05-22	15:15	cojo	Stiv	5	CUMPLEAÑOS	88552147	2026-05-22 13:03:35.142948
4	quispe	tan	RES-40313FE2	2026-05-22 13:33:49.350256	tan@gmail.com	COMPLETADA	A la carta	2026-05-22	16:45	nose\n	emilia	4	salcedo	785522651	2026-05-22 13:34:35.87247
\.


--
-- TOC entry 4473 (class 0 OID 0)
-- Dependencies: 220
-- Name: reservas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservas_id_seq', 55, true);


--
-- TOC entry 4316 (class 2606 OID 17440)
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id);


--
-- TOC entry 4318 (class 2606 OID 17442)
-- Name: reservas ukb2ahxlt3kuwhhnsf4ccs1tdl6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT ukb2ahxlt3kuwhhnsf4ccs1tdl6 UNIQUE (codigo);


-- Completed on 2026-06-06 14:02:24 -05

--
-- PostgreSQL database dump complete
--

\unrestrict L6YmxKmnHpaSZm6hdYKSAcgtfDdga4aQc7hakV8ZbQ78hIaabsRZzU6YB2imX91

