server.servlet.context-path=/

# PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/mesas_db
spring.datasource.write.username=postgres
spring.datasource.write.password=kenyiaqp10
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5433/mesas_db
spring.datasource.read.username=postgres
spring.datasource.read.password=kenyiapq10
spring.datasource.read.driver-class-name=org.postgresql.Driver

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
