version: "3.9"
x-service-defaults: &service-defaults
  restart: always
x-service-env: &service-env
  SPRING_PROFILES_ACTIVE: docker
  EUREKA_URL: ${EUREKA_URL}
  WRITE_SERVER: ${WRITE_SERVER}
  READ_SERVER: ${READ_SERVER}
  WRITE_PORT: ${WRITE_PORT}
  READ_PORT: ${READ_PORT}
  USERNAME_WRITE_DB: ${USERNAME_WRITE_DB}
  PASSWORD_WRITE_DB: ${PASSWORD_WRITE_DB}
  USERNAME_READ_DB: ${USERNAME_READ_DB}
  PASSWORD_READ_DB: ${PASSWORD_READ_DB}
  ACCESS_KEY: ${ACCESS_KEY}
  SECRET_KEY: ${SECRET_KEY}
services:
  # =====================================================
  # EUREKA SERVER
  # =====================================================
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    image: italomoroco/eureka-server:latest
    ports:
      - "8761:8761"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
  # =====================================================
  # GATEWAY
  # =====================================================

  gateway-server:
    <<: *service-defaults
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: Gateway-Server
    image: italomoroco/gateway-server:latest

    ports:
      - "8090:8090"

    environment:
      <<: *service-env
      FRONTEND_URL: ${FRONTEND_URL}

  # =====================================================
  # CAMBIOS
  # =====================================================

  microservicio-cambios:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-cambios

    image: italomoroco/microservicio-cambios:latest

    ports:
      - "8081:8081"
    environment:
      <<: *service-env

  # =====================================================
  # COCINA
  # =====================================================

  microservicio-cocina:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-cocina

    image: italomoroco/microservicio-cocina:latest

    ports:
      - "8218:8218"

    environment:
      <<: *service-env
  # =====================================================
  # EVENTOS
  # =====================================================

  microservicio-eventos:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-eventos

    image: italomoroco/microservicio-eventos:latest

    ports:
      - "8215:8215"
    environment:
      <<: *service-env

  # =====================================================
  # INSUMOS
  # =====================================================

  microservicio-insumos:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Insumos

    image: italomoroco/microservicio-insumos:latest

    ports:
      - "8100:8100"
    environment:
      <<: *service-env

  # =====================================================
  # MERMAS
  # =====================================================

  microservicio-mermas:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Mermas

    image: italomoroco/microservicio-mermas:latest

    ports:
      - "8300:8300"
    environment:
      <<: *service-env

  # =====================================================
  # PAGOS
  # =====================================================

  microservicio-pagos:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pagos

    image: italomoroco/microservicio-pagos:latest

    ports:
      - "8219:8219"
    environment:
      <<: *service-env

  # =====================================================
  # PEDIDOS
  # =====================================================

  microservicio-pedidos:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pedidos

    image: italomoroco/microservicio-pedidos:latest

    ports:
      - "8217:8217"
    environment:
      <<: *service-env

  # =====================================================
  # PRODUCTOS
  # =====================================================

  microservicio-producto:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-producto

    image: italomoroco/microservicio-producto:latest

    ports:
      - "8083:8083"
    environment:
      <<: *service-env

  # =====================================================
  # PROVEEDOR
  # =====================================================

  microservicio-proveedor:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-proveedor

    image: italomoroco/microservicio-proveedor:latest

    ports:
      - "8200:8200"
    environment:
      <<: *service-env

  # =====================================================
  # RESERVAS
  # =====================================================

  microservicio-reservas:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-reservas

    image: italomoroco/microservicio-reservas:latest

    ports:
      - "8082:8082"
    environment:
      <<: *service-env

  # =====================================================
  # USERS
  # =====================================================

  microservicio-users:
    <<: *service-defaults

    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: users

    image: italomoroco/microservicio-users:latest

    ports:
      - "8220:8220"

    environment:
      <<: *service-env