version: "3.9"
services:
  # =====================================================
  # EUREKA SERVER
  # =====================================================
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
  # =====================================================
  # GATEWAY SERVER
  # =====================================================
  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: Gateway-Server
    container_name: gateway-server
    ports:
      - "8090:8090"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka
      FRONTEND_URL: http://localhost:4200
      SECRET: mysecretkey
    depends_on:
      - eureka-server

  # =====================================================
  # COCINA
  # =====================================================
  microservicio-cocina:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-cocina
    container_name: microservicio-cocina
    ports:
      - "8218:8218"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      COCINA_WRITE_DB: cocina-write-db:5432
      COCINA_READ_DB: cocina-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - cocina-write-db
      - cocina-read-db

  cocina-write-db:
    image: postgres:16
    container_name: cocina-write-db
    restart: always
    environment:
      POSTGRES_DB: cocina_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - cocina_write_data:/var/lib/postgresql/data

  cocina-read-db:
    image: postgres:16
    container_name: cocina-read-db
    restart: always
    environment:
      POSTGRES_DB: cocina_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - cocina_read_data:/var/lib/postgresql/data

  # =====================================================
  # EVENTOS
  # =====================================================
  microservicio-eventos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-eventos
    container_name: microservicio-eventos
    ports:
      - "8215:8215"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      EVENTOS_WRITE_DB: eventos-write-db:5432
      EVENTOS_READ_DB: eventos-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - eventos-write-db
      - eventos-read-db

  eventos-write-db:
    image: postgres:16
    container_name: eventos-write-db
    restart: always
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - eventos_write_data:/var/lib/postgresql/data

  eventos-read-db:
    image: postgres:16
    container_name: eventos-read-db
    restart: always
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - eventos_read_data:/var/lib/postgresql/data

  # =====================================================
  # INSUMOS
  # =====================================================
  microservicio-insumos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Insumos
    container_name: microservicio-insumos
    ports:
      - "8100:8100"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      INSUMOS_WRITE_DB: insumos-write-db:5432
      INSUMOS_READ_DB: insumos-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - insumos-write-db
      - insumos-read-db

  insumos-write-db:
    image: postgres:16
    container_name: insumos-write-db
    restart: always
    environment:
      POSTGRES_DB: insumos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - insumos_write_data:/var/lib/postgresql/data

  insumos-read-db:
    image: postgres:16
    container_name: insumos-read-db
    restart: always
    environment:
      POSTGRES_DB: insumos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - insumos_read_data:/var/lib/postgresql/data

  # =====================================================
  # MERMAS
  # =====================================================
  microservicio-mermas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Mermas
    container_name: microservicio-mermas
    ports:
      - "8300:8300"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      MERMAS_WRITE_DB: mermas-write-db:5432
      MERMAS_READ_DB: mermas-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - mermas-write-db
      - mermas-read-db

  mermas-write-db:
    image: postgres:16
    container_name: mermas-write-db
    restart: always
    environment:
      POSTGRES_DB: mermas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - mermas_write_data:/var/lib/postgresql/data

  mermas-read-db:
    image: postgres:16
    container_name: mermas-read-db
    restart: always
    environment:
      POSTGRES_DB: mermas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - mermas_read_data:/var/lib/postgresql/data

  # =====================================================
  # PAGOS
  # =====================================================
  microservicio-pagos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pagos
    container_name: microservicio-pagos
    ports:
      - "8219:8219"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      PAGOS_WRITE_DB: pagos-write-db:5432
      PAGOS_READ_DB: pagos-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - pagos-write-db
      - pagos-read-db

  pagos-write-db:
    image: postgres:16
    container_name: pagos-write-db
    restart: always
    environment:
      POSTGRES_DB: pagos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5441:5432"
    volumes:
      - pagos_write_data:/var/lib/postgresql/data

  pagos-read-db:
    image: postgres:16
    container_name: pagos-read-db
    restart: always
    environment:
      POSTGRES_DB: pagos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - pagos_read_data:/var/lib/postgresql/data

  # =====================================================
  # PEDIDOS
  # =====================================================
  microservicio-pedidos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pedidos
    container_name: microservicio-pedidos
    ports:
      - "8217:8217"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      PEDIDOS_WRITE_DB: pedidos-write-db:5432
      PEDIDOS_READ_DB: pedidos-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - pedidos-write-db
      - pedidos-read-db

  pedidos-write-db:
    image: postgres:16
    container_name: pedidos-write-db
    restart: always
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"
    volumes:
      - pedidos_write_data:/var/lib/postgresql/data

  pedidos-read-db:
    image: postgres:16
    container_name: pedidos-read-db
    restart: always
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - pedidos_read_data:/var/lib/postgresql/data

  # =====================================================
  # PRODUCTOS
  # =====================================================
  microservicio-producto:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-producto
    container_name: microservicio-producto
    ports:
      - "8083:8083"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      PRODUCTOS_WRITE_DB: productos-write-db:5432
      PRODUCTOS_READ_DB: productos-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - productos-write-db
      - productos-read-db

  productos-write-db:
    image: postgres:16
    container_name: productos-write-db
    restart: always
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
    volumes:
      - productos_write_data:/var/lib/postgresql/data

  productos-read-db:
    image: postgres:16
    container_name: productos-read-db
    restart: always
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5446:5432"
    volumes:
      - productos_read_data:/var/lib/postgresql/data

  # =====================================================
  # PROVEEDOR
  # =====================================================
  microservicio-proveedor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservice-proveedor
    container_name: microservicio-proveedor
    ports:
      - "8200:8200"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      PROVEEDOR_WRITE_DB: proveedor-write-db:5432
      PROVEEDOR_READ_DB: proveedor-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - proveedor-write-db
      - proveedor-read-db

  proveedor-write-db:
    image: postgres:16
    container_name: proveedor-write-db
    restart: always
    environment:
      POSTGRES_DB: proveedores_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5447:5432"
    volumes:
      - proveedor_write_data:/var/lib/postgresql/data

  proveedor-read-db:
    image: postgres:16
    container_name: proveedor-read-db
    restart: always
    environment:
      POSTGRES_DB: proveedores_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5448:5432"
    volumes:
      - proveedor_read_data:/var/lib/postgresql/data

  # =====================================================
  # RESERVAS
  # =====================================================
  microservicio-reservas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-reservas
    container_name: microservicio-reservas
    ports:
      - "8082:8082"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka

      RESERVAS_WRITE_DB: reservas-write-db:5432
      RESERVAS_READ_DB: reservas-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - reservas-write-db
      - reservas-read-db

  reservas-write-db:
    image: postgres:16
    container_name: reservas-write-db
    restart: always
    environment:
      POSTGRES_DB: reserva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5449:5432"
    volumes:
      - reservas_write_data:/var/lib/postgresql/data

  reservas-read-db:
    image: postgres:16
    container_name: reservas-read-db
    restart: always
    environment:
      POSTGRES_DB: reserva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5450:5432"
    volumes:
      - reservas_read_data:/var/lib/postgresql/data

  # =====================================================
  # USERS
  # =====================================================
  microservicio-users:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: users
    container_name: microservicio-users
    ports:
      - "8220:8220"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://eureka-server:8761/eureka
      SECRET: mysecretkey

      USERS_WRITE_DB: users-write-db:5432
      USERS_READ_DB: users-read-db:5432

      USERNAME_WRITE_DB: postgres
      PASSWORD_WRITE_DB: postgres
      USERNAME_READ_DB: postgres
      PASSWORD_READ_DB: postgres
    depends_on:
      - eureka-server
      - users-write-db
      - users-read-db

  users-write-db:
    image: postgres:16
    container_name: users-write-db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5451:5432"
    volumes:
      - users_write_data:/var/lib/postgresql/data

  users-read-db:
    image: postgres:16
    container_name: users-read-db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5452:5432"
    volumes:
      - users_read_data:/var/lib/postgresql/data

volumes:
  cocina_write_data:
  cocina_read_data:
  eventos_write_data:
  eventos_read_data:
  insumos_write_data:
  insumos_read_data:
  mermas_write_data:
  mermas_read_data:
  pagos_write_data:
  pagos_read_data:
  pedidos_write_data:
  pedidos_read_data:
  productos_write_data:
  productos_read_data:
  proveedor_write_data:
  proveedor_read_data:
  reservas_write_data:
  reservas_read_data:
  users_write_data:
  users_read_data: