name: restaurante-backend
services:
  eureka-server:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: italomoroco/eureka-server:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8761
        published: "8761"
        protocol: tcp
    restart: always
  gateway-server:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: Gateway-Server
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      FRONTEND_URL: https://le-bon-gout.vercel.app/
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/gateway-server:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8090
        published: "8090"
        protocol: tcp
    restart: always
  microservicio-cambios:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-cambios
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-cambios:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8081
        published: "8081"
        protocol: tcp
    restart: always
  microservicio-cocina:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-cocina
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-cocina:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8218
        published: "8218"
        protocol: tcp
    restart: always
  microservicio-eventos:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservice-eventos
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-eventos:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8215
        published: "8215"
        protocol: tcp
    restart: always
  microservicio-insumos:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Insumos
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-insumos:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8100
        published: "8100"
        protocol: tcp
    restart: always
  microservicio-mermas:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservice-Mermas
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-mermas:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8300
        published: "8300"
        protocol: tcp
    restart: always
  microservicio-pagos:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pagos
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-pagos:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8219
        published: "8219"
        protocol: tcp
    restart: always
  microservicio-pedidos:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-pedidos
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-pedidos:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8217
        published: "8217"
        protocol: tcp
    restart: always
  microservicio-producto:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservice-producto
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-producto:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8083
        published: "8083"
        protocol: tcp
    restart: always
  microservicio-proveedor:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservice-proveedor
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-proveedor:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8200
        published: "8200"
        protocol: tcp
    restart: always
  microservicio-reservas:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: microservicio-reservas
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-reservas:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8082
        published: "8082"
        protocol: tcp
    restart: always
  microservicio-users:
    build:
      context: /home/italo/Programación/Restaurante/Restaurante-Backend
      dockerfile: Dockerfile
      args:
        MODULE: users
    environment:
      ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
      EUREKA_URL: eureka-server.railway.internal
      PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
      READ_PORT: "49707"
      READ_SERVER: kodama.proxy.rlwy.net:49707
      SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
      SPRING_PROFILES_ACTIVE: docker
      USERNAME_READ_DB: postgres
      USERNAME_WRITE_DB: postgres
      WRITE_PORT: "49707"
      WRITE_SERVER: kodama.proxy.rlwy.net:49707
    image: italomoroco/microservicio-users:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8220
        published: "8220"
        protocol: tcp
    restart: always
networks:
  default:
    name: restaurante-backend_default
x-service-defaults:
  restart: always
x-service-env:
  ACCESS_KEY: AKIAX4A3UIVOTDEKKJ5Y
  EUREKA_URL: eureka-server.railway.internal
  PASSWORD_READ_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
  PASSWORD_WRITE_DB: msfvdWmZSYavABnKdvafxKWPcfWjjGUH
  READ_PORT: "49707"
  READ_SERVER: kodama.proxy.rlwy.net:49707
  SECRET_KEY: DQN70vOJN9W8cMMwvp6w3JPQ2wWfrY2pftDnc1Ra
  SPRING_PROFILES_ACTIVE: docker
  USERNAME_READ_DB: postgres
  USERNAME_WRITE_DB: postgres
  WRITE_PORT: "49707"
  WRITE_SERVER: kodama.proxy.rlwy.net:49707
