spring.application.name=microservicio-mermas
server.port=8300
server.servlet.context-path=/

# Configuracion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mermas_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.level.com.microservicio.Mermas=DEBUG