# Configuracion PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://${MERMAS_WRITE_DB}/mermas_db
spring.datasource.write.username=${USERNAME_WRITE_DB}
spring.datasource.write.password=${PASSWORD_WRITE_DB}
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.jdbc-url=jdbc:postgresql://${MERMAS_READ_DB}/mermas_db
spring.datasource.read.username=${USERNAME_READ_DB}
spring.datasource.read.password=${USERNAME_READ_DB}
spring.datasource.read.driver-class-name=org.postgresql.Driver

# Logging
logging.level.com.microservicio.Mermas=DEBUG
