spring.application.name=microservicio-pagos
server.port=8219
server.servlet.context-path=/
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/pagos_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Eureka (deshabilitado para pruebas)
eureka.client.enabled=true
pdf.storage.path=./pdfs/