# PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/pagos_db
spring.datasource.write.username=postgres
spring.datasource.write.password=kenyiaqp10
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5433/pagos_db
spring.datasource.read.username=postgres
spring.datasource.read.password=kenyiaqp10
spring.datasource.read.driver-class-name=org.postgresql.Driver

pdf.storage.path=./pdfs/

eureka.client.enabled=false
spring.cloud.discovery.enabled=false
