spring.application.name=microservice-reservas
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.database=postgresql
spring.database-platform=org.hibernate.dialect.PostgresSQLDialect
spring.profiles.default=local