spring.application.name=reserva
server.port=8082
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/reserva
spring.datasource.username=postgres
spring.datasource.password=kenyiaqp10
spring.jpa.hibernate.ddl-auto=update
spring.database=postgresql
spring.database-platform=org.hibernate.dialect.PostgresPlusDialect
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.enabled=false
