server:
  port: 8220
spring:
  profiles:
    default: local
  application:
    name: microservice-users
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
    sql:
      init:
        mode: always
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}