jwt:
  secret: "3KTMZ7An77+TnowBQVy0+Nop3ADuwmIIbcTszYkOAYY="
spring:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/users_db
      username: postgres
      password: kenyiaqp10
      driver-class-name: org.postgresql.Driver

    read:
      jdbc-url: jdbc:postgresql://localhost:5433/users_db
      username: postgres
      password: kenyiaqp10
      driver-class-name: org.postgresql.Driver
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    enabled: false