--
-- PostgreSQL database dump
--

\restrict o15dFKV1Nl6Elb5tnTmLR9JC6Gdj7CJhYuAiCLKTxfljRziqyyhO3w0s52EEr7u

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-06 14:00:54 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17348)
-- Name: comprobantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comprobantes (
    id bigint NOT NULL,
    correlativo integer NOT NULL,
    created_at timestamp without time zone,
    mesa_numero integer NOT NULL,
    numero_completo character varying(255) NOT NULL,
    orden_id character varying(255) NOT NULL,
    pdf_url character varying(255),
    razon_social character varying(255),
    ruc character varying(255),
    serie character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    total double precision NOT NULL
);


ALTER TABLE public.comprobantes OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17361)
-- Name: comprobantes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comprobantes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comprobantes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17362)
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    estado character varying(255) NOT NULL,
    mesa_numero integer NOT NULL,
    metodo character varying(255) NOT NULL,
    orden_id character varying(255) NOT NULL,
    total double precision NOT NULL,
    CONSTRAINT pagos_metodo_check CHECK (((metodo)::text = ANY (ARRAY[('EFECTIVO'::character varying)::text, ('TARJETA'::character varying)::text, ('QR'::character varying)::text])))
);


ALTER TABLE public.pagos OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17374)
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4473 (class 0 OID 17348)
-- Dependencies: 219
-- Data for Name: comprobantes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comprobantes (id, correlativo, created_at, mesa_numero, numero_completo, orden_id, pdf_url, razon_social, ruc, serie, tipo, total) FROM stdin;
1	1	2026-05-21 15:47:58	1	B001-00000001	ORD-1779394599519	./pdfs/B001-00000001.pdf	\N	\N	B001	BOLETA	48
2	1	2026-05-21 16:03:59	3	F001-00000001	ORD-1779394653379	./pdfs/F001-00000001.pdf	SACA LOCO SAC	12121212121	F001	FACTURA	118
3	2	2026-05-21 16:09:45	1	B001-00000002	ORD-1779394599519	./pdfs/B001-00000002.pdf	\N	\N	B001	BOLETA	84
\.


--
-- TOC entry 4475 (class 0 OID 17362)
-- Dependencies: 221
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagos (id, created_at, estado, mesa_numero, metodo, orden_id, total) FROM stdin;
1	2026-05-21 15:47:58.076442	PAGADO	1	EFECTIVO	ORD-1779394599519	48
2	2026-05-21 16:03:59.254325	PAGADO	3	TARJETA	ORD-1779394653379	118
3	2026-05-21 16:09:45.290142	PAGADO	1	QR	ORD-1779394599519	84
\.


--
-- TOC entry 4482 (class 0 OID 0)
-- Dependencies: 220
-- Name: comprobantes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comprobantes_id_seq', 21, true);


--
-- TOC entry 4483 (class 0 OID 0)
-- Dependencies: 222
-- Name: pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_id_seq', 39, true);


--
-- TOC entry 4321 (class 2606 OID 17376)
-- Name: comprobantes comprobantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT comprobantes_pkey PRIMARY KEY (id);


--
-- TOC entry 4325 (class 2606 OID 17378)
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- TOC entry 4323 (class 2606 OID 17380)
-- Name: comprobantes ukaax9o8wa0p6xc8l1uh0asgekv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comprobantes
    ADD CONSTRAINT ukaax9o8wa0p6xc8l1uh0asgekv UNIQUE (numero_completo);


-- Completed on 2026-06-06 14:00:54 -05

--
-- PostgreSQL database dump complete
--

\unrestrict o15dFKV1Nl6Elb5tnTmLR9JC6Gdj7CJhYuAiCLKTxfljRziqyyhO3w0s52EEr7u

