# Configuracion PostgreSQL
spring.datasource.write.url=jdbc:postgresql://${PRODUCTOS_WRITE_DB}/productos_db
spring.datasource.write.username=${USERNAME_WRITE_DB}
spring.datasource.write.password=${PASSWORD_WRITE_DB}
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.url=jdbc:postgresql://${PRODUCTOS_READ_DB}/productos_db
spring.datasource.read.username=${USERNAME_READ_DB}
spring.datasource.read.password=${PASSWORD_READ_DB}
spring.datasource.read.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true