spring.application.name=microservicio-producto
server.port=8080
server.servlet.context-path=/

# Configuracion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/productos_db
spring.datasource.username=postgres
spring.datasource.password=kenyiaqp10
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Multipart (para imágenes)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true

# Logging
logging.level.com.microservicio.Producto=DEBUG