--
-- PostgreSQL database dump
--

\restrict v7EM6xCG7IdlHluobUSROrjOOOWsPQROl29xS50axh0ypshWmEQtBCtBquUc8HO

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-06 14:02:41 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17444)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    apellido character varying(50) NOT NULL,
    clave character varying(255) NOT NULL,
    dni character varying(8) NOT NULL,
    email character varying(255) NOT NULL,
    nombre character varying(50) NOT NULL,
    tipo character varying(255) NOT NULL,
    idusuario integer NOT NULL,
    CONSTRAINT usuario_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('CLIENTE'::character varying)::text, ('MESERO'::character varying)::text, ('COCINERO'::character varying)::text, ('ADMINISTRADOR'::character varying)::text])))
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17457)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17493)
-- Name: usuario_idusuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN idusuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_idusuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4469 (class 0 OID 17444)
-- Dependencies: 219
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, apellido, clave, dni, email, nombre, tipo, idusuario) FROM stdin;
5	Clavijo	$2a$10$s3d/tnJb7WZdkeKzL6Pv0e3lX7sfNbJq9GdU/xXSek8sRcy43ANe.	1236985	xd4@gmail.com	Sir	CLIENTE	1
10	Puma	$2a$10$Rs0Aw0fdjeBWflRsD9GnKeraJakDSkQcBW9fX3Q3A5HLEGtO.H0ce	78996354	javier@res.com	Javier	COCINERO	2
11	Clavijo	$2a$10$5aKcNdv3DfW7bhe1bE3oGeiA0AWn4N2CEDGX9HBlh9fooRNxaHa0S	72125555	sir@gmail.com	Sir	CLIENTE	3
12	san	$2a$10$m6lAwgG8/ZkJXz/mtdFQpOA6J2RJomDQBzRPFPvr1YZGkDm1unxjG	9876543	dino@res.com	dino	CLIENTE	4
6	Gomez	$2a$10$EKkEdj5qwjtl4mv9tkgJYuyVBhUlnuuhQ8NyygAy13kbv2Xi/KCpa	12345678	admin@lebongout.com	Admin	ADMINISTRADOR	5
13	Clavijo	$2a$10$OeAPrgiFHgv0ZS5OjD5kYOS29MSzZe6QDjonPsrimqPu4oE.Z7jg.	72129951	jack@res.com	Jack	ADMINISTRADOR	6
14	moroco	$2a$10$N5atyLA9PvTDnHg6wM17Peu6bJbcVflqSTnGWoB9HFTtq2/h0DB3W	75126689	italo@res.com	italo	MESERO	7
\.


--
-- TOC entry 4477 (class 0 OID 0)
-- Dependencies: 220
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 411, true);


--
-- TOC entry 4478 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuario_idusuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_idusuario_seq', 404, true);


--
-- TOC entry 4317 (class 2606 OID 17459)
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- TOC entry 4319 (class 2606 OID 17461)
-- Name: usuario ukma71x4n4tydibsd9qt0m71le7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT ukma71x4n4tydibsd9qt0m71le7 UNIQUE (dni);


--
-- TOC entry 4321 (class 2606 OID 17463)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


-- Completed on 2026-06-06 14:02:41 -05

--
-- PostgreSQL database dump complete
--

\unrestrict v7EM6xCG7IdlHluobUSROrjOOOWsPQROl29xS50axh0ypshWmEQtBCtBquUc8HO

