--
-- PostgreSQL database dump
--

\restrict ugFvzkQvbjocs0fSBfD7E4bWcbPdHX7zsecsstYo2Pb7DvgA5N8xrSfSTffxgKT

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-06 13:57:29 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 17229)
-- Name: evento_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evento_requests (
    id bigint NOT NULL,
    age_confirmed boolean NOT NULL,
    attendees integer NOT NULL,
    comments character varying(1000) NOT NULL,
    company character varying(255),
    created_at timestamp(6) without time zone,
    event_date date NOT NULL,
    email character varying(255) NOT NULL,
    last_name character varying(100) NOT NULL,
    marketing_accepted boolean,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    privacy_accepted boolean NOT NULL,
    source character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT evento_requests_source_check CHECK (((source)::text = ANY ((ARRAY['WEB_FORM'::character varying, 'PHONE'::character varying, 'WALK_IN'::character varying])::text[]))),
    CONSTRAINT evento_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'RECIBIDO'::character varying, 'CANCELADO'::character varying])::text[])))
);


ALTER TABLE public.evento_requests OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17228)
-- Name: evento_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evento_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4466 (class 0 OID 17229)
-- Dependencies: 220
-- Data for Name: evento_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evento_requests (id, age_confirmed, attendees, comments, company, created_at, event_date, email, last_name, marketing_accepted, name, phone, privacy_accepted, source, status, updated_at) FROM stdin;
2	t	32	wwwwddddddddddddddddddddddddddddddddddddddddddddddas	dawdwaddd	2026-05-16 17:49:02.294443	2026-05-27	dawd@gmail.com	dawdawa	t	patrpocp	122555333	t	WEB_FORM	RECIBIDO	2026-05-16 17:56:54.977984
11	t	150	sadawdadawdawdawdawdawd	Los purc	2026-05-19 17:58:57.194176	2026-05-28	castillo@gmail.com	Castillo	f	Pedro	945411654	t	WEB_FORM	PENDIENTE	2026-05-19 17:58:57.194176
12	t	23	dawdawdwadawdawd	Los dimno	2026-05-19 17:59:31.733872	2026-05-28	kill@gmail.com	Perez	f	Jorgfe	465465454	t	WEB_FORM	PENDIENTE	2026-05-19 17:59:31.733872
13	t	123	dwadawdawdwdd	Los incas	2026-05-19 18:00:38.036821	2026-05-22	xd@gmail.com	YUPANQUI	f	Patroclo	942635964	t	WEB_FORM	PENDIENTE	2026-05-19 18:00:38.036821
14	t	32	dawdawdawdawd	Los incas	2026-05-19 18:00:58.464341	2026-05-22	xd@gmail.com	Roe	f	Patroclo2	992072614	t	WEB_FORM	PENDIENTE	2026-05-19 18:00:58.464341
15	t	232	dawdawddddd	Los incas	2026-05-19 18:01:14.90854	2026-05-28	xd@gmail.com	YUPANQUI	f	Arnold	942635962	t	WEB_FORM	PENDIENTE	2026-05-19 18:01:14.909897
16	t	132	2222w12eawdawd	Los incas	2026-05-19 18:01:35.601308	2026-05-29	xd@gmail.com	Roe	f	Arnold	992072614	t	WEB_FORM	PENDIENTE	2026-05-19 18:01:35.601308
17	t	22	dawdawdwadawd	dawdwaddd	2026-05-19 18:01:50.166169	2026-05-28	xd@gmail.com	YUPANQUI	f	dawdaw	992072614	t	WEB_FORM	PENDIENTE	2026-05-19 18:01:50.166169
18	t	33	dawdawdawdaw	212e	2026-05-19 18:02:06.851184	2026-06-02	xd@gmail.com	YUPANQUI	f	Rodolfo	942635962	t	WEB_FORM	PENDIENTE	2026-05-19 18:02:06.851184
19	t	33	dawdawdawdawd	Los incas	2026-05-19 18:02:28.151637	2026-05-29	xd@gmail.com	Perez	f	Arnold	942635962	t	WEB_FORM	PENDIENTE	2026-05-19 18:02:28.151637
21	t	233	dawdawdawdawdwa	Los incas	2026-05-19 18:03:12.068882	2026-07-08	xd@gmail.com	Perez	f	xd	231232132	t	WEB_FORM	RECIBIDO	2026-05-19 18:03:35.654947
20	t	122	dawdawdawd	Los incas	2026-05-19 18:02:43.756078	2026-06-25	xd@gmail.com	Perez	f	Arnold	942635962	t	WEB_FORM	RECIBIDO	2026-05-19 18:03:36.644563
23	t	50	Evento empresarial importante.	Acme	2026-05-20 16:03:59.7157	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:03:59.715888
24	t	50	Evento empresarial importante.	Acme	2026-05-20 16:04:00.181353	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:04:00.181432
25	t	50	Evento empresarial importante.	Acme	2026-05-20 16:04:00.367918	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:04:00.368001
26	t	50	Evento empresarial importante.	Acme	2026-05-20 16:04:00.576241	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:04:00.576355
27	t	50	Evento empresarial importante.	Acme	2026-05-20 16:06:23.077667	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:06:23.077904
28	t	50	Evento empresarial importante.	Acme	2026-05-20 16:06:23.380483	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:06:23.380578
29	t	50	Evento empresarial importante.	Acme	2026-05-20 16:06:23.791432	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:06:23.79153
30	t	50	Evento empresarial importante.	Acme	2026-05-20 16:06:24.056193	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:06:24.056295
31	t	50	Evento empresarial importante.	Acme	2026-05-20 16:26:36.292656	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:26:36.292806
32	t	50	Evento empresarial importante.	Acme	2026-05-20 16:26:36.557254	2026-05-25	juan@test.com	Perez	f	Juan	+51999999999	t	WEB_FORM	PENDIENTE	2026-05-20 16:26:36.557337
\.


--
-- TOC entry 4472 (class 0 OID 0)
-- Dependencies: 219
-- Name: evento_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evento_requests_id_seq', 46, true);


--
-- TOC entry 4317 (class 2606 OID 17249)
-- Name: evento_requests evento_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evento_requests
    ADD CONSTRAINT evento_requests_pkey PRIMARY KEY (id);


-- Completed on 2026-06-06 13:57:30 -05

--
-- PostgreSQL database dump complete
--

\unrestrict ugFvzkQvbjocs0fSBfD7E4bWcbPdHX7zsecsstYo2Pb7DvgA5N8xrSfSTffxgKT

