# Configuracion PostgreSQL
spring.datasource.write.url=jdbc:postgresql://localhost:5432/insumos_db
spring.datasource.write.username=postgres
spring.datasource.write.password=admin
spring.datasource.write.driver-class-name=org.postgresql.Driver

spring.datasource.read.url=jdbc:postgresql://localhost:5432/insumos_db
spring.datasource.read.username=postgres
spring.datasource.read.password=admin
spring.datasource.read.driver-class-name=org.postgresql.Driver
eureka.client.service-url.defaultZone=http://localhost:8761/eureka