server.port=8081
spring.application.name=microservicio-solicitudes
# ===== EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ========== JIRA CONFIGURATION ==========
jira.url=https://utp-restaurante.atlassian.net
jira.username=U21318614@utp.edu.pe
jira.token=ATATT3xFfGF0XgAtS81ufknYGrRt-LZylECzU-PbY7vuebgWEXoC3E3rBNynJSikIFQCwuXwDc1F_myjojkXdWO7O7tDxptsgW6U4uVcU8lMIM9FftunTHlVV7620x7n1Rzm54Xn-2vyBca0fYbog1Vur4DkWuepGAALgSTyI8lTEWYWlKo1LZQ=6D4DA6FF
jira.project.key=SOLICITUD
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# ========== LOGGING ==========
logging.level.com.microservicio.cambio=DEBUG
# Estos microservicios usan JIRA en todo momento, no hay sentido en crear un perfil especial para ellos
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
