# Configuracion PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/proveedores_db
spring.datasource.write.username=postgres
spring.datasource.write.password=kenyiaqp10
spring.datasource.write.driver-class-name=org.postgresql.Driver

#spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5432/proveedores_db
spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5433/proveedores_db
spring.datasource.read.username=postgres
spring.datasource.read.password=kenyiaqp10
spring.datasource.read.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.discovery.client.composite-indicator.enabled=true
eureka.client.enabled=false


# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG