spring.application.name=microservicio-proveedor
server.port=8200
# Configuracion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proveedor_db
spring.datasource.username=postgres
spring.datasource.password=kenyiaqp10
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.discovery.client.composite-indicator.enabled=true
# Configuracion de pool de conexiones
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

# Actuator (opcional, para monitoreo)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
