spring:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://${EVENTOS_WRITE_DB}/eventos_db
      username: ${USERNAME_WRITE_DB}
      password: ${PASSWORD_WRITE_DB}
      driver-class-name: org.postgresql.Driver
    read:
      jdbc-url: jdbc:postgresql://${EVENTOS_READ_DB}/eventos_db
      username: ${USERNAME_READ_DB}
      password: ${USERNAME_PASSWORD_DB}
      driver-class-name: org.postgresql.Driver
    # Configuracion de Eureka (Service Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}