spring:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/eventos_db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    read:
      #jdbc-url: jdbc:postgresql://localhost:5433/eventos_db
      jdbc-url: jdbc:postgresql://localhost:5433/eventos_db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    enabled: false