spring:
  application:
    name: microservicio-eventos
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8215
# Configuracion de CORS (override en Gateway)
management:
  endpoints:
    web:
      exposure:
        include: health,info