spring.datasource.write.driver-class-name=org.postgresql.Driver
spring.datasource.write.jdbc-url=jdbc:postgresql://${RESERVAS_WRITE_DB}/reserva
spring.datasource.write.username=${USERNAME_WRITE_DB}
spring.datasource.write.password=${PASSWORD_WRITE_DB}

spring.jpa.datasource.read.driver-class-name=org.postgresql.Driver
spring.datasource.read.jdbc-url=jdbc:postgresql://${RESERVAS_READ_DB}/reserva
spring.datasource.read.username=${USERNAME_READ_DB}
spring.datasource.read.password=${PASSWORD_READ_DB}