spring.datasource.write.driver-class-name=org.postgresql.Driver
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/reservas_db
spring.datasource.write.username=postgres
spring.datasource.write.password=kenyiaqp10

#Como vosotros no tienen la replica SOLO cambian el puerto de 5433 a 5432 para que ambos apunten a la misma base de datos
spring.datasource.read.driver-class-name=org.postgresql.Driver
spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5433/reservas_db
spring.datasource.read.username=postgres
spring.datasource.read.password=kenyiaqp10