name: CI-Cocina
on:
  pull_request:
    branches:
      - master
    paths:
      - 'microservicio-cocina/**'
  push:
    branches:
      - master
    paths:
      - 'microservicio-cocina/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres-write:
        image: postgres:16
        env:
          POSTGRES_DB: cocina_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      postgres-read:
        image: postgres:16
        env:
          POSTGRES_DB: cocina_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup & install java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
      - name: Install postgresql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Wait for postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres
          do
            echo "Waiting for postgres-write"
            sleep 2
          done
          
          
          until pg_isready -h localhost -p 5433 -U postgres
          do
            echo "Waiting for postgres-read"
            sleep 2
          done
      - name: Load schema into write database
        run: |
          PGPASSWORD=kenyiaqp10 psql \
          -h localhost \
          -p 5432 \
          -U postgres \
          -d cocina_db \
          -f microservicio-cocina/database/schema_cocina.sql
      - name: Load schema into read database
        run: |
          PGPASSWORD=kenyiaqp10 psql \
          -h localhost \
          -p 5433 \
          -U postgres \
          -d cocina_db \
          -f microservicio-cocina/database/schema_cocina.sql
      - name: Run tests
        working-directory: microservicio-cocina
        run: mvn clean test -Dspring.profiles.active=tests
      - name: Build application
        working-directory: microservicio-cocina
        run: mvn clean package -DskipTests
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cocina-artifact
          path: microservicio-cocina/target/*.jar
      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cocina-tests-reports
          path: microservicio-cocina/target/surefire-reports/
